# Site settings
title: HyunWook, Hong
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: HyunWook, Hong
user_description: Training program for direct interpretation, java, Aug,2016<br/>shooting game using to java, Fall semester,2016<br/>the games using to LeapMotion, Unity C#script, Jan,2017<br/>Web for locker application, <a href='http://kmuce.com'>PHP</a>, Feb,2017<br/>VR windows using to HTC VIVE, Unity C#script, Jun,2017<br/>SE project_Study Mate(Schedule Management and Word Learning), Java/JDBC, Spring semester,2018<br/>SP project_vim extension based on <a href="https://github.com/antirez/kilo">kilo</a> ANSI-C, Fall semester,2018<br/>Capstone_Application for foreign students using O2O service, Corperation:경북대 국제교류처/(주)더인, Android Spring-framework firebase, Fall semester,2018<br/>한국뇌공학회/경북대 주관, 인공지능 특강 이수, Feb, 2019<br/>Capstone_Mobile device security authentication and Media server control app development on iOS, Corperation:(주)조은캠프, Swift, Spring semester,2019<br/>한국정보화진흥원(NIA)주관, <a href='./PublicData_R/'>공공데이터활용</a> 교육 이수, Oct,2019<br/>

user_title: Bachelor of CSE at KNU
email: hwhong.korea@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
